name: Dependabot Labels

on:
  pull_request:
    types:
      - labeled

jobs:
  dependabot-pr-label:
    if: >-
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot labeled PR
        run: echo "Dependabot labeled a PR with label ${{ inputs.pr_label }}"
